# Generated by Django 5.2.5 on 2025-08-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='amount_to_pay',
            field=models.IntegerField(default=1000),
        ),
    ]
